export type CementerioRow = {
    id: string;
    nicho: string;
    folio: string;
    tipo: string;
    ocupante: string;
    numero_orden: string;
    tiene_lapida: boolean;
    es_socio: boolean;
    socio_id: string | null;
    persona_id: string | null;
    paga_por: string;
    anio_de_gracia: string;
    contrato_nro: string;
    contrato_por_anios: string;
    anio_venc_contrato: string;
    ultimo_pago: string;
    plan_de_pago: string;
    fecha_de_pago: string;
    telefono: string;
    nombre_alternativo: string;
    fecha_fallecimiento: string;
    created_at: string;
    updated_at: string;
};

export type PersonRow = {
    id: string;
    nombre: string;
    tipo_doc: string | null;
    documento: string | null;
    domicilio: string | null;
    telefono: string | null;
    created_at: string;
};

export type ServiceRecordRow = {
    id: string;
    service_id: string | null;
    member_id: string | null;
    person_id: string | null;
    movement_id: string | null;
    amount: number;
    date: string;
    detail: string | null;
    created_at: string;
    updated_at: string;
};

export type ServiceRecordWithDetails = {
    id: string;
    service_id: string | null;
    service_name: string | null;
    service_amount: number | null;
    member_id: string | null;
    member_nombre: string | null;
    member_numero_de_socio: string | null;
    person_id: string | null;
    person_nombre: string | null;
    movement_id: string | null;
    movement_amount: number | null;
    amount: number;
    date: string;
    service_date: string | null;
    detail: string | null;
    created_at: string;
    updated_at: string;
};

export type MemberRow = {
    id: string;
    numero_de_socio: string;
    nombre: string;
    sexo: string | null;
    residencia: string | null;
    nro_familia: string | null;
    nro_fam_a_fall: string | null;
    tipo_doc: string | null;
    documento: string | null;
    cuil: string | null;
    tipo_socio: string | null;
    fecha_nac: string | null;
    edad: string | null;
    cod_postal: string | null;
    localidad: string | null;
    domicilio: string | null;
    email: string | null;
    telefono: string | null;
    asistencial: boolean;
    plan_salud: boolean;
    militar: boolean;
    fuerza: string | null;
    grado: string | null;
    estado: string | null;
    fecha_ingreso: string | null;
    fecha_baja: string | null;
    motivo_baja: string | null;
    cobra_iaf: string | null;
    paga_por: string | null;
    depositar_en: string | null;
    cementerio: string | null;
    fallecido: boolean;
    apoderado1_id: string | null;
    apoderado2_id: string | null;
    apoderado1_nombre: string | null;
    apoderado1_tipo_doc: string | null;
    apoderado1_documento: string | null;
    apoderado1_domicilio: string | null;
    apoderado1_telefono: string | null;
    apoderado2_nombre: string | null;
    apoderado2_tipo_doc: string | null;
    apoderado2_documento: string | null;
    apoderado2_domicilio: string | null;
    apoderado2_telefono: string | null;
};
